# Generated by Django 5.2.3 on 2025-06-21 09:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0003_quest_context_quest_personalized_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reflection',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='reflection',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
